# Stage 1: Builder
FROM golang:latest AS builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the local package files to the container's workspace.
COPY . ./

# Installing dependencies and building
RUN CGO_ENABLED=0 GOOS=linux go build -o /gocd

# Stage 2: Final Image
FROM alpine:latest

# Copy the executable from the builder stage
COPY --from=builder /gocd ./app


# Grant execution permissions to the executable
RUN chmod +x ./app

# Expose port 9000
EXPOSE 9000

# Command to run the executable
CMD ["./app"]
